config/routes.rb
Rails.application.routes.draw do
  resources :lyrics, except: [:show]
  get 'lyrics/login'

  scope controller: :pages do
    get :navbar
    get :words
    get :quotes
    get :fade
    get :fax
    get :lotus
  end

  get '/:name', to: 'pages#redirect'

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lyric.rb
class Lyric < ApplicationRecord
  has_rich_text :content

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
  before_action :set_body
  before_action :set_lyric, only: [:edit, :update, :destroy]

  before_action :authenticate_admin!, except: [:login]
  http_basic_authenticate_with name: "laundrymen", password: "gridwave", only: [:login]

  def login
    session[:admin_token] = "8JZ8tzq3FWNjHio4FczZLfte"
    redirect_to lyrics_path
  end

  def index
    @lyrics = Lyric.all.order(title: :asc)
  end

  def new
    @lyric = Lyric.new
  end

  def create
    @lyric = Lyric.new(lyric_params)

    if @lyric.save
      redirect_to lyrics_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @lyric.update(lyric_params)
      redirect_to lyrics_path
    else
      render :edit
    end
  end

  def destroy
    @lyric.destroy
    redirect_to lyrics_path
  end

  private

  def lyric_params
    params.require(:lyric).permit(:title, :content)
  end

  def set_lyric
    @lyric = Lyric.find(params[:id])
  end

  def set_body
    @body_classes = %w[black full-height lyrical]
  end

  def authenticate_admin!
    redirect_to lyrics_login_path unless logged_in?
  end

  def logged_in?
    session[:admin_token] == "8JZ8tzq3FWNjHio4FczZLfte"
  end
end

app/controllers/pages_controller.rb
require 'open-uri'

class PagesController < ApplicationController
  def home
  end

  def navbar
    html = render_to_string template: 'pages/_navbar', layout: false
    render json: {
      html: html
    }
  end

  def words
    @body_classes = ["black", "full-height"]

    # included_pos = "noun,adjective,verb,adverb,interjection,preposition,idiom,imperative,noun-plural,verb-intransitive,verb-transitive"
    included_pos = "noun"
    # all possible POS: abbreviation, adjective, adverb, affix, article, auxiliary-verb, conjunction, combining-form, definite-article, family-name, given-name, idiom, imperative, indefinite-article, interjection, noun-plural, noun, noun-singular, participle, past-participle, prefix, phrasal-verb, preposition, pronoun, proper-noun-plural, proper-noun, suffix, verb-intransitive, verb-transitive, verb
    url = "http://api.wordnik.com:80/v4/words.json/randomWords?hasDictionaryDef=true&minCorpusCount=0&minLength=5&maxLength=15&limit=5&includePartOfSpeech=#{included_pos}&api_key=#{ENV['WORDNIK_API_KEY']}"
    @words = JSON.load(open(url)).map { |wd| wd["word"] }
  end

  def quotes
    @body_classes = ["black", "full-height"]
  end

  def fade
    @body_classes = ["black", "full-height"]

    @text = [
      [:away, 'https://www.'],
      [:stay, 'lushed.co', root_path],
      [:away, '/fade']
    ]
  end

  def fax
    @body_classes = ["black", "full-height"]
  end

  def lotus
    @body_classes = ["black", "full-height"]
  end

  def redirect
    # redirect to various links
    name = params[:name].to_sym
    links = {
      chaw: 'https://docs.google.com/presentation/d/1eY4_R_kQwX4HwMs4KcJZtNrtfEtmgu1HfsLPugFpv5Q/edit',
    }
    redirect_to links[name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_body_classes
    unless @body_classes.nil?
      return @body_classes.is_a?(String) ? @body_classes : @body_classes.join(" ")
    end
  end

  def google_search(terms)
    terms = terms.join("+") if terms.is_a?(Array)
    "https://www.google.com/search?q=#{terms}"
  end

  def link_to_if(*args,&block)
    args.insert 1, capture(&block) if block_given?

    super *args
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>lushed</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class="<%= render_body_classes %>">
    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <%= yield(:after_js) %>
  </body>
</html>

app/views/lyrics/_form.html.erb
<%= simple_form_for @lyric do |f| %>
  <%= f.input :title %>

  <%= f.rich_text_area :content %>

  <br />
  <br />
  <%= f.submit class: 'button' %>
<% end %>

app/views/lyrics/create.html.erb
<h1>Lyrics#create</h1>
<p>Find me in app/views/lyrics/create.html.erb</p>

app/views/lyrics/destroy.html.erb
<h1>Lyrics#destroy</h1>
<p>Find me in app/views/lyrics/destroy.html.erb</p>

app/views/lyrics/edit.html.erb
<%= render 'shared/back', text: 'all lyrics', href: lyrics_path %>

<div class="container">
  <br />
  <h1><%= @lyric.title %></h1>
  <%= render 'form' %>

  <br />
  <br />
  <br />
  <br />
  <br />
  <%= link_to "delete lyric", lyric_path(@lyric), method: :delete, data: { confirm: "are you sure? you can't undo this!" }, class: 'red' %>
</div>

app/views/lyrics/index.html.erb
<%= render 'shared/back' %>

<div class="flex-center full-height">
  <div>
    <h1>lyrics</h1>

    <hr>

    <ul class="no-list-markup">
      <% @lyrics.each do |lyric| %>
        <li class="tall-line-height">* <%= link_to lyric.title, edit_lyric_path(lyric) %></li>
      <% end %>
    </ul>

    <hr>

    <p><%= link_to "new lyric", new_lyric_path %></p>
  </div>
</div>

app/views/lyrics/new.html.erb
<%= render 'shared/back', text: 'all lyrics', href: lyrics_path %>

<div class="container">
  <br />
  <h1>new lyric</h1>
  <%= render 'form' %>
</div>

app/views/lyrics/update.html.erb
<h1>Lyrics#update</h1>
<p>Find me in app/views/lyrics/update.html.erb</p>

app/views/pages/_navbar.html.erb
<div class="navbar">
  <p id="back">lushed</p>

  <% links = ["words", "quotes", "fade", "lotus"] %>
  <% links.each do |link| %>
    <%= link_to link, send("#{link}_path") %>
  <% end %>
</div>

app/views/pages/fade.html.erb
<div class="flex-center text-center full-height">
  <h2 class="text-fade">
    <% @text.each do |text| %><%= link_to_if !text[2].nil?, text[2] do %><span class="<%= text[0] %>"><%= text[1] %></span><% end %><% end %>
  </h2>
</div>

<% content_for(:after_js) do %>
  <script>
    $(function() {
      var $away = $('.text-fade .away');
      var interval = 20;
      var amount = 0.0009;
      var intervalID;

      function fade() {
        var opacity = $away.css('opacity');
        if (opacity <= 0) {
          clearInterval(intervalID);
        } else {
          $away.css('opacity', opacity - amount);
        }
      }

      intervalID = setInterval(fade, interval);

      function set_title(title) {
        $(document).attr("title", title);
      }

      var index = 0;
      var thing = ".";
      var word = "lushed";

      function update_title() {
        var title = word.split("");
        title.splice(index % (title.length + 1), 0, thing);
        set_title(title.join(""));
        index++;
      }

      setInterval(update_title, 2700);
    });
  </script>
<% end %>

app/views/pages/fax.html.erb
<%= render 'shared/back' %>

<div class="flex-center text-center full-height">
  <p>did you know humans drink &#x221e;&times; less water when they are asleep than when they are alive?</p>
</div>

app/views/pages/home.html.erb
<%= render 'navbar' %>

<div class="text-center" style="margin-top: 100px;">
  <%= link_to "lushed.co", root_path, class: "link" %>
  <br>
  <%= link_to "lyrics", lyrics_path, class: "link" %>
</div>

app/views/pages/lotus.html.erb
<%= render 'shared/back' %>

<div class="full-height flex-center text-center"
     style="background: url('https://images.unsplash.com/photo-1533274814154-b8dc5f18c0f8?auto=format&w=1440&q=90') no-repeat center center fixed;">

  <div>
    <p>lotus</p>
    <br>
    <p class="text-left line-height-breathe text-shadow">
      <i>
      how letters of words form petals of flowers<br>
      how words in lines form ponds of thoughts<br>
      take fleurs and hours make smell of decay<br>
      rake hay for hours and make flour powder<br>
      like little red hen had no real friends but faux ones<br>
      bread still stale and sour tho musky decay
      </i>
    </p>
  </div>

  <p class="lushed lushed-bottom lushed-right stealth">photo: <a href="https://unsplash.com/photos/hhrADG91TAY" target="_blank">Echo Yan</a></p>
</div>

app/views/pages/quotes.html.erb
<%= render 'shared/back' %>

<div class="flex-center text-center full-height">
  <div id="quotes">
    <div class="quote">
      <p>As the gig economy grows, so too does the danger that engineers, in attempting to build the most efficient systems, will chop and dice jobs into pieces so dehumanized that our legal system will no longer recognize them.<br>And along with this comes an even more sinister possibility: jobs that <i>would</i> and <i>should</i> be recognizable — especially supervisory and management positions — will disappear altogether. If a software engineer can write a set of programs that breaks a job into smaller increments, and can follow it up with an algorithm that fills in as the supervisor, then the position itself can be programmed to redundancy.</p>
      <p class="by">Susan Fowler, 2018</p>
      <!-- https://www.vanityfair.com/news/2018/08/silicon-valley-engineers-fear-they-created-a-monster -->
    </div>
    <div class="quote">
      <p>They’re just chords, just melodies. I don’t know what combination of those objects is gonna make me feel how I need to feel. But I know precisely the feeling that needs to happen.</p>
      <p class="by">Frank Ocean</p>
      <!-- https://www.nytimes.com/2016/11/20/arts/music/frank-ocean-blonde-interview.html -->
    </div>
  </div>
</div>

app/views/pages/words.html.erb
<%= render 'shared/back' %>

<div class="flex-center text-center full-height">
  <ul class="no-list-markup">
    <% @words.each do |word| %>
      <li class="tall-line-height"><%= link_to word, google_search(word), target: "_blank", class: 'no-href-markup' %></li>
    <% end %>

    <br>
    <li class="tall-line-height stealth"><%= link_to "all", google_search(@words), target: "_blank", class: 'no-href-markup stealth' %></li>
  </ul>
</div>

app/views/shared/_back.html.erb
<% extra_classes ||= "" %>
<% href ||= root_path %>
<% text ||= "lushed" %>

<p class="lushed lushed-top lushed-left #{extra_classes}"><%= link_to text, href, id: 'back' %></p>